### ISSUE TITLE
Package versions

### ISSUE THREAD

**Issue by umarikkar** [bozeklab/lmagp#2]
Could you please share the torch, lightning and hydra versions please, thanks

**Comment by juanigp** [comment]
Hi, these are the versions of the packages

    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - hydra-zen==0.6.0
    - lightning==2.0.1
    - pytorch-lightning==2.0.1
    - tensorboard==2.10.0
    - torch==2.0.1
    - torchmetrics==0.11.4
    - transformers==4.23.1
    - pandas

**Comment by juanigp** [comment]
Just uploaded a .yaml file with the required dependencies
